### ISSUE TITLE
scala 2.13 is not relased

### ISSUE THREAD

**Issue by borissmidt** [VirtusLab/scala-yaml#102]
It seems that there is a version for 2.12 and 3 but not 2.13

**Comment by borissmidt** [comment]
I guess i have to use the `.cross(CrossVersion.for2_13Use3)`

**Comment by kpodsiad** [comment]
It's strange that there's released `2.12`, it's probably due to some misconfiguration in publishing script.

Just like you wrote, with `.cross(CrossVersion.for2_13Use3)` you should be able to consume `3` version. In addition to this, you should also add scalac option `Ytasty-reader` [(see this)](https://youtu.be/k-eP7SPjcwE?t=460).

**Comment by kpodsiad** [comment]
2.12 is no longer published - fixed in https://github.com/VirtusLab/scala-yaml/pull/124
