### ISSUE TITLE
All non-printable characters must be escaped

### ISSUE THREAD

**Issue by novakov-alexey** [VirtusLab/scala-yaml#216]
I am comparing scala-yaml parser with Circe JSON
```scala
Char.MinValue.toString.as[String].foreach(println) // prints nothing
> ""
println(Char.MinValue.toString.asJson) // circe lib code is called, ".asJson"
> \u0000
```
According to [YAML specification](https://yaml.org/spec/1.2.2/#57-escaped-characters), all non-printable characters must be escaped. Is it a bug in scala-yaml?

**Comment by novakov-alexey** [comment]
@kpodsiad did you check whether scala-yaml somehow compliant to https://yaml.org/spec/1.2.2/ YAML specification?
Should I ignore any other similar issues?

**Comment by lbialy** [comment]
it is *somewhat* compliant, I guess we'll leave this open for now and see whether this should be fixed in future

**Comment by lbialy** [comment]
@novakov-alexey this is a more complex problem than it looks. First of all, your code example is not equivalent:
`Char.MinValue.toString.as[String]` using scala-yaml parses the string as yaml and returns `Left(org.virtuslab.yaml.ComposerError: Expected YAML node, but found: StreamEnd)` so that's why your `.foreach(println)` doesn't print anything. In contrast: `println(Char.MinValue.toString.asJson)` is a call to `final def asJson(implicit encoder: Encoder[A]): Json = encoder(value)` method, which does only the encoding step. The scala-yaml equivalent would be `.asYaml`. Unfortunately `.asYaml` does not print anything too and this is an actual problem, because it means we are not escaping special chars when printing yaml.
